name: Go package test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          go-version: [ '1.14', '1.15', '1.20' ]

    steps:
      - uses: actions/checkout@v3

      - name: Create Nats cluster
        uses: onichandame/nats-action@master
        with:
          port: "4222 4223 4224"      

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...